### ISSUE TITLE
attempted relative import in non-package python

### ISSUE THREAD

**Issue by richardzulu** [gabrielfalcao/lettuce#431]
Whenever I run python manage.py harvest, I receive a traceback call as depicted

```
Traceback (most recent call last):
File   "/home/xxxx/programming/apps/xxxxx/sipi/src/lettuce/lettuce/django/management/commands/harvest.py", line 185, in handle
result = runner.run()
File "/home/xxxxx/programming/apps/xxxx/sipi/src/lettuce/lettuce/__init__.py", line 148, in run
self.loader.find_and_load_step_definitions()
File "/home/xxxxx/programming/apps/xxxxxx/sipi/src/lettuce/lettuce/fs.py", line 58, in   find_and_load_step_definitions
raise e
ValueError: Attempted relative import in non-package when importing  /home/xxxx/programming/apps/xxxx/sipi/local/lib/python2.7/site- packages/debug_toolbar/utils.py
```

**Comment by danni** [comment]
Okay, this is a bug in the feature loader when combined with relative imports, i.e. one step file importing things from another step file using relative imports.

**Comment by danni** [comment]
There's a fix for this on https://github.com/infoxchange/lettuce/tree/new-parser

Although it requires your steps directory to be importable as part of your Python package to work (i.e. you need `__init__.py` files. Alternatively consider [Aloe](https://github.com/koterpillar/aloe), which is next generation Lettuce based on nose (and takes a whole bunch of the code from `new-parser`).
