### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hjwp** [gabrielfalcao/lettuce#458]
Apologies if this is being tracked elsewhere, I did have a look.

First hurdle: currently requirements.txt won't install under python 3.  The pinned version of `coverage` and `markment` seem to be the cause.  Unpinning coverage gets you further, but markment seems to require an old version of Flask which won't work under Py3.

```
Downloading/unpacking flask==0.9 (from markment->-r requirements.txt (line 17))
  Using download cache from /home/harry/.pip-download-cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2FF%2FFlask%2FFlask-0.9.tar.gz
  Running setup.py (path:/home/harry/.virtualenvs/lettuce/build/flask/setup.py) egg_info for package flask
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/harry/.virtualenvs/lettuce/build/flask/setup.py", line 62
        print "Audit requires PyFlakes installed in your system."
                                                                ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/harry/.virtualenvs/lettuce/build/flask/setup.py", line 62

    print "Audit requires PyFlakes installed in your system."

                                                            ^

SyntaxError: invalid syntax
```

**Comment by geokala** [comment]
I'm also interested in python3 support. I'd open another issue but I couldn't title it better, so:
Do any of the maintainers have any input on this? Is there any development already in progress for python3 support or is this a case of "try it and start submitting pull requests"?

If the latter, how would tests best work for this particular compatibility feature? Running them in multiple versions of python by hand is of course an option but it doesn't seem to fit the spirit of a project about testing.

**Comment by KarstenSchulz** [comment]
+1 for Py3 support

**Comment by danni** [comment]
So I don't think Python 3 is going to happen in Lettuce unless someone takes it over. I had been doing it, but I've now moved all of my energy across to Aloe, which is a fork of Lettuce/new-parser that runs as a Nose plugin.

**Comment by nikolas** [comment]
I'll try and come up with a pull request for python 3

**Comment by nikolas** [comment]
lettuce relies on markment, which uses Flask 0.9, which isn't compatible with Python 3. There's a pull request to address this here: https://github.com/gabrielfalcao/markment/pull/4

**Comment by nikolas** [comment]
A big chunk of work here will be converting everything in lettuce's tests directory to be compatible with python3's improved unicode support while maintaining compatibility with python 2. We can use [six](https://pypi.python.org/pypi/six) for this.

**Comment by rg3915** [comment]
Lettuce support Python 3 is done?

**Comment by nikolas** [comment]
No, I have a branch I was working on, but it's a work in progress.

**Comment by fkromer** [comment]
@nikolas: may one contribute to your lettuce fork?

**Comment by nikolas** [comment]
@fkromer here's the branch I'm referring to if you're interested in continuing this work: https://github.com/nikolas/lettuce/tree/python3

**Comment by fkromer** [comment]
@nikolas i am not very experienced at porting from 2.x to 3.x but i would give it a try and contribute. I had a look at six and wondered that it is not using the module 2to3 from the standard library?

**Comment by nikolas** [comment]
Yeah, both [six](https://pypi.python.org/pypi/six) and [future](https://pypi.python.org/pypi/future) can be useful when writing code compatible for python 2 and 3.

Here's a good cheat sheet: http://python-future.org/compatible_idioms.html

**Comment by AlexzAK** [comment]
Why pull request with python 3 patch isn't merged?
Do you have python 3 support in plans?

**Comment by raeisi** [comment]
Is there any chance to get this Python 3 Support up and running faster?

If not does anyone know of any other BDD TDD Cucamber like environment for Python3?

**Comment by geokala** [comment]
behave works reasonably well in my experience. Some irritations but that's always the way when coming to a new framework.

**Comment by danni** [comment]
Aloe attempts to pick up where Lettuce leaves off. Uses the official
Gherkin parser.

**Comment by Naereen** [comment]
Hi all,
This was never finished?
It's too bad, Python 2 is really dead now, and lettuce sound(s/ed) exciting!

**Comment by sgpy** [comment]
Umm... still an open item. Let me take a stab, and see if it gets anywhere.

**Comment by sgpy** [comment]
@nikolas Did you get a chance to complete the migration? So far i have encountered some minor problem with mox.

**Comment by sgpy** [comment]
@Naereen @raeisi @AlexzAK @fkromer @nikolas @rg3915 @hjwp @geokala 
> Hello folks - Have a working [lettuce](https://github.com/sgpy/lettuce.git) __py3__ branch ready for beta testing which supports py27 & py37 (refer CHANGELOGS.md for changes). I do plan to merge it once i get some feedback for you all. 

### Testing
#### PY2
##### All  passing
#### PY3
##### UNIT - All Passing
##### FUNCTIONAL - Four test cases which needs to retrospectively fix during change in source code line numbers & subtle unicode values hardcoded in the test cases

**Comment by sgpy** [comment]
@gabrielfalcao @nikolas  Any feedback? Wanted to send in a merge request.

**Comment by nikolas** [comment]
@sgpy  I mean.. that looks great. I would love to merge a pull request like this. But the first step toward getting that merged isn't opening it in this repo... rather, moving this repo to a new organization that people other than @gabrielfalcao actually have admin access to, as he seems to have moved on.

If you want to make progress here, try and get lettuce into https://jazzband.co/.

**Comment by sgpy** [comment]
@nikolas agree & i think that is the right way forward. Do you have a lead which i can track at Jazzband?

**Comment by chris-piekarski** [comment]
Your python3 fork works good for me @sgpy

**Comment by sgpy** [comment]
@chris-piekarski great to hear that. Cheers....

**Comment by nikolas** [comment]
@sgpy the process for transferring a project to jazzband is outlined here: https://jazzband.co/about/guidelines

I'm not sure how exactly you do the transfer, but I would join their IRC room and ask around there: https://jazzband.co/about/contact

**Comment by danni** [comment]
Lettuce users are encouraged to take a look at [Aloe](https://github.com/aloetesting/aloe), which grew out of an attempt to port Lettuce to Python 3 and fix up the bugs in the parser.

**Comment by sgpy** [comment]
@nikolas Awesome. Meanwhile i will try and close open issues (as much as possible) on the main line. Let me know how things progress with JazzBand.

@danni [Aloe](https://github.com/aloetesting/aloe) is the most logical step forward for [lettuce](https://github.com/gabrielfalcao/lettuce) users. However, i feel confident migrating my codebase to py37, and then moving to __Aloe__. Happy to contribute towards __Aloe__ codebase too (if required).

**Comment by fdcds** [comment]
There was a PR for Python 3 support back in the day: #324

**Comment by nikolas** [comment]
Well, my team just re-wrote all our lettuce tests in [Cypress](https://www.cypress.io/), so that's one way to move forward here.

**Comment by sugizo** [comment]
```
$ python -V
Python 3.8.5
$ conda -V
conda 4.9.2
$ lettuce
Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/bin/lettuce", line 5, in <module>
    from lettuce.bin import main
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/lettuce/__init__.py", line 179
    print "Error loading step definitions:\n", e
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Error loading step definitions:\n", e)?
```

is this error related to python 3 support ?

thanks
