### ISSUE TITLE
Mixing inclusion and exclusion tags causes unexpected behaviour

### ISSUE THREAD

**Issue by rtkaheller** [gabrielfalcao/lettuce#498]
###### Feature file:
```gherkin
Feature: Lettuce tags

  @include_tag @exclude_tag
  Scenario: This test should be skipped
    Given a test
    Then this test is not run

  @include_tag
  Scenario: This test should be run
    Given a test
    Then this test is run
```
###### Python file:
```python
from lettuce import step

@step('a test')
def a_test(step):
  pass

@step('this test is not run')
def not_run(step):
  assert False

@step('this test is run')
def run(step):
  assert True
```

##### Expected Result:
Running ```lettuce --tag=include_tag --tag=-exclude_tag``` will run only the second scenario
```

Feature: Lettuce tags                   # features/tags.feature:1
  @include_tag @exclude_tag             # features/tags.feature:3

  @include_tag
  Scenario: This test should be run# features/tags.feature:9
    Given a test                        # features/tags.py:4
    Then this test is run               # features/tags.py:12

1 feature (1 passed)
1 scenario (1 passed)
2 steps (2 passed)
```

##### Actual Result
Running ```lettuce --tag=include_tag --tag=-exclude_tag``` runs both scenarios
```

Feature: Lettuce tags                   # features/tags.feature:1
  @include_tag @exclude_tag             # features/tags.feature:3

  @include_tag @exclude_tag
  Scenario: This test should be skipped# features/tags.feature:4
    Given a test                        # features/tags.py:4
    Then this test is not run           # features/tags.py:8
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lettuce/core.py", line 141, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/rtkaheller/lettuce_tags/features/tags.py", line 9, in not_run
        assert False
    AssertionError

  @include_tag
  Scenario: This test should be run# features/tags.feature:9
    Given a test                        # features/tags.py:4
    Then this test is run               # features/tags.py:12

1 feature (0 passed)
2 scenarios (1 passed)
4 steps (1 failed, 3 passed)
```

This behaviour means there is no way to run all scenarios that match tag "a" but don't match tag "b".

**Comment by lawnmowerlatte** [comment]
I'd like to second this. I was hoping to use `lettuce -t tag1 -t tag2 -t -wip` so that my CI build won't run any in progress scenarios.
