### ISSUE TITLE
Improperly configured with lettuce 0.2.23

### ISSUE THREAD

**Issue by MironMar** [gabrielfalcao/lettuce#529]
Hi

I installed new version of lettuce and after calling `./manage.py harvest` I get this error:

```Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/miron/.virtualenvs/talixo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/miron/.virtualenvs/talixo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/miron/.virtualenvs/talixo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/miron/.virtualenvs/talixo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 42, in load_command_class
    return module.Command()
  File "/home/miron/.virtualenvs/talixo/local/lib/python2.7/site-packages/django/core/management/base.py", line 228, in __init__
    '"requires_system_checks".' % self.__class__.__name__)
django.core.exceptions.ImproperlyConfigured: Command Command defines both "requires_model_validation" and "requires_system_checks", which is illegal. Use only "requires_system_checks".
```

However it works fine on 0.2.22.

**Comment by ramast** [comment]
It has been fixed aparently
https://github.com/gabrielfalcao/lettuce/blob/master/lettuce/django/management/commands/harvest.py

Replace line
        `requires_model_validation = requires_system_checks = False`
With the one in the repo

```
    if DJANGO_VERSION < StrictVersion('1.7'):
        requires_model_validation = False
    else:
        requires_system_checks = False
```

**Comment by gummoe** [comment]
This change doesn't seem to be reflected in the current PyPi package here: https://pypi.python.org/pypi/lettuce/0.2.23. The last upload was on 2016-07-26.
