### ISSUE TITLE
Django 1.9  Application labels aren't unique, duplicates: django

### ISSUE THREAD

**Issue by x007007007** [gabrielfalcao/lettuce#548]
```
Traceback (most recent call last):
  File "/Users/xxc/.virtualenvs/funnyface/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/xxc/.virtualenvs/funnyface/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/xxc/.virtualenvs/funnyface/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/xxc/.virtualenvs/funnyface/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/xxc/.virtualenvs/funnyface/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/xxc/.virtualenvs/funnyface/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: django
```
my setting file like:
```
INSTALLED_APPS = [
      ....
    'lettuce.django',
]
```

**Comment by x007007007** [comment]
My config duplicate installed apps, sorry
